server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://101.43.17.123:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 809fdg~AE@57
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  redis:
    host: 101.43.17.123 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 323&dhfqdWQ41
    timeout: 300ms # 连接超时时间（毫秒）
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost

wx:
  mp:
    aesKey: '@aesKey'
    appId: wx0c7247818e8a7662
    secret: 5e527f9635ab12c8ec883f6a8bc96c50
    token: '@token'


